Pass --workspace whenever target != current
Avoids a strange bug compiling dependnecies.

Running `cargo check -p syn` in the root dir gives:

thread 'main' panicked at 'activated_features for invalid package: features did not find PackageId { name: "syn", version: "1.0.85", source: "registry `crates-io`" } false', src/tools/cargo/src/cargo/core/resolver/features.rs:296:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Presumably because of mismatched features :(